In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from dca.methods_comparison import JPCA, symmJPCA

In [3]:
import numpy as np

In [23]:
# Synthetic LDS
n = 6
A = np.random.rand(n, n)
rho = np.max(np.abs(np.linalg.eigvals(A)))
A = A * (0.9 / rho)

B = np.random.rand(n, 1)
C = np.eye(n)
Q = np.eye(n)
R = np.eye(n) * 0.1

# Define the initial state and noise
x0 = np.random.rand(n,)
w = np.random.multivariate_normal(np.zeros(n), Q, size=1000)
v = np.random.multivariate_normal(np.zeros(n), R, size=1000)

# Simulate the system
y = []
x = x0
for i in range(1000):
    y.append(np.dot(C, x) + v[i])
    x = np.dot(A, x) + w[i]

# Convert the output to a NumPy array
y = np.array(y)

In [30]:
j1 = JPCA(mean_subtract=False)
j2 = symmJPCA(mean_subtract=False)

In [38]:
j1.fit(y[np.newaxis, :, :])

[[ 0.          0.0030341  -0.00388198 -0.00200945  0.00091825  0.01159508]
 [-0.0030341   0.          0.08449393 -0.02690001 -0.05326507  0.097648  ]
 [ 0.00388198 -0.08449393  0.          0.02414042 -0.0560993   0.03227707]
 [ 0.00200945  0.02690001 -0.02414042  0.         -0.03015136 -0.02963248]
 [-0.00091825  0.05326507  0.0560993   0.03015136  0.          0.02634476]
 [-0.01159508 -0.097648   -0.03227707  0.02963248 -0.02634476  0.        ]]


In [33]:
j1.eigen_vals_

array([ 0.15812898, -0.15812898,  0.05030167, -0.05030167,  0.01079993,
       -0.01079993])

In [57]:
j2.fit(y[np.newaxis, :, :])

[[-0.84267717  0.18262221  0.19500639  0.05684081  0.2121093   0.15784925]
 [ 0.18262221 -1.01168561  0.1246508   0.12028392  0.16344617  0.19402849]
 [ 0.19500639  0.1246508  -0.75494698  0.16827326  0.078352    0.04774874]
 [ 0.05684081  0.12028392  0.16827326 -0.82267497  0.11855531  0.14109258]
 [ 0.2121093   0.16344617  0.078352    0.11855531 -0.6963662   0.1351131 ]
 [ 0.15784925  0.19402849  0.04774874  0.14109258  0.1351131  -0.82427817]]


In [36]:
j2.eigen_vals_

array([-0.116602  , -0.80571629, -0.90228842, -0.90228842, -1.07561774,
       -1.15011624])

In [ ]:
# Test implementation in 2 ways: 
# 1. Fit to data generated from symmetric matrix
# 2. Compare implementation of optimize asymmetric to to existing jpca

In [100]:
# Fitting to symmetric matrix
n = 6
A = np.random.rand(n, n)
A = 0.5 * (A + A.T)
rho = np.max(np.abs(np.linalg.eigvals(A)))
A = A * (0.9 / rho)

B = np.random.rand(n, 1)
C = np.eye(n)
Q = np.eye(n)
R = np.eye(n) * 0.1

n_samples = int(1e5)

# Define the initial state and noise
x0 = np.random.rand(n,)
w = np.random.multivariate_normal(np.zeros(n), Q, size=n_samples)
v = np.random.multivariate_normal(np.zeros(n), R, size=n_samples)

# Simulate the system
y = []
x = x0
for i in range(n_samples):
    y.append(np.dot(C, x))
    x = np.dot(A, x) + w[i]
    
# Convert the output to a NumPy array
y = np.array(y)

In [102]:
j2 = symmJPCA(mean_subtract=False)

In [103]:
j2.fit(y[np.newaxis, :, :])

600683.7126256281
600683.7126256281
[[-0.88568845  0.11990941  0.18170124  0.13959471  0.13267993  0.03747054]
 [ 0.11990941 -0.85087768  0.06370438  0.20188383  0.2736869   0.15795216]
 [ 0.18170124  0.06370438 -0.79708659  0.07303351  0.14846175  0.15010286]
 [ 0.13959471  0.20188383  0.07303351 -0.83153034  0.18120218  0.25804429]
 [ 0.13267993  0.2736869   0.14846175  0.18120218 -0.94854859  0.18512472]
 [ 0.03747054  0.15795216  0.15010286  0.25804429  0.18512472 -0.98035299]]


In [105]:
A - np.eye(A.shape[0])

array([[-0.88552812,  0.11882086,  0.18173697,  0.13986472,  0.13323338,
         0.03880408],
       [ 0.11882086, -0.84922727,  0.0639477 ,  0.20271134,  0.2735374 ,
         0.15931138],
       [ 0.18173697,  0.0639477 , -0.79495712,  0.07417237,  0.14910271,
         0.14872604],
       [ 0.13986472,  0.20271134,  0.07417237, -0.83148483,  0.17960636,
         0.2562409 ],
       [ 0.13323338,  0.2735374 ,  0.14910271,  0.17960636, -0.95095882,
         0.18737732],
       [ 0.03880408,  0.15931138,  0.14872604,  0.2562409 ,  0.18737732,
        -0.98271126]])